### ISSUE TITLE
Is there some references on  general_constrastive_loss_layer?

### ISSUE THREAD

**Issue by chendd14** [happynear/NormFace#10]
ContrastiveLoss in often used in Siamese Network Training, it needs pairs of data, which is very different from your implementations in this experiment. Would you please tell me the reason.

**Comment by chendd14** [comment]
######### Contrastive Loss#############
layer {
  name: "slice_data"
  type: "Slice"
  bottom: "fc7_norm"
  top: "fc7_norm1"
  top: "fc7_norm2"
  include { 
    phase: TRAIN
  }
  slice_param {
    axis: 0
  }
}
layer {
  name: "slice_label"
  type: "Slice"
  bottom: "label"
  top: "label1"
  top: "label2"
  include { 
    phase: TRAIN
  }
  slice_param {
    axis: 0
  }
}
layer {
  name: "contrastive_loss"
  type: "ContrastiveLoss"
  bottom: "fc7_norm1"
  bottom: "fc7_norm2"
  bottom: "label1"
  bottom: "label2"
  loss_weight: 0.1
  top: "contrastive_loss"
  include { 
    phase: TRAIN
  }
  contrastive_loss_param {
    margin: 1.0
  }
}
########################

**Comment by happynear** [comment]
Have you seen my paper? I wrote the reason in Section 4.

**Comment by happynear** [comment]
Maybe it should not be named as general_contrastive_loss. But when I wrote this layer, I didn't come up with the C-Contrastive loss yet. Anyway, it is just a name...

**Comment by chendd14** [comment]
@happynear Thanks, I put my attention on features and parameters normalization in SoftMax. I will read your paper again.
