### ISSUE TITLE
Confused about Figure 4 Left.

### ISSUE THREAD

**Issue by kalyo-zjl** [happynear/NormFace#11]
Hi, @happynear 

When I read your paper, I feel confused about Figure 4 Left.
The question is that why should vector x and gradient of x be orthogonal, since Loss is not a unit circle function? And thus, the Pythagoras theorem may not hold. So, I don't quite understand the Figure 4 Left. 
Could you please explain it further?

Thanks.

**Comment by happynear** [comment]
This figure is not about the loss function. It's only about the normalize layer. The gradient from loss function to the normlized x can be of any direction as the figure shows. In fact, I just drew a line arbitarily to represent the gradient of the normalized x.

But through the normalize layer, the gradient will be projected to the tangent space of vector x. This can be inferred from the equation. Actually, if we let the point walk on the sphere, the gradient can only be orthogonal to x. I think this is not difficult to imagine because we all learned about the pendulum motion problem. 

Since I don't know some of the terminology in English and you are also a Chinese, I will explain it in Chinese.

就像以前做的受力分析，分析钟摆下端小球的受力，我们需要分解成切向力和法向力，然后因为绳子拉住了小球，所以法向力被忽略了，在这里也是一样的，法向力被归一化层直接弄没了。

而且如果你还记得线性代数的话，会发现公式4的分子部分就是施密特正交化的公式，它一定是跟x正交的。

**Comment by kalyo-zjl** [comment]
Thanks for your reply. But I think I feel more confused.
First, in your paper, It is said below Equation 4 that 
![1](https://user-images.githubusercontent.com/19725489/27718662-f35f3bb0-5d7f-11e7-89b1-f041322f09c3.JPG)
It may not be true that L can be any kind of loss function, even if we do normalization on x first. For example, if x=(u, v) and L=u^2+2v^2.
Besides, I also can't find relationship between numerator of Equation4 and Gram–Schmidt process which is 
![2](https://user-images.githubusercontent.com/19725489/27718849-2d728a72-5d81-11e7-9ea3-c0a06f6d52f5.JPG)
Though similar, they are different.
InnerProduct of Equation 4 and x can't get 0 either.

**Comment by happynear** [comment]
The loss function can only give gradient to \tilde{x}. For example a loss function may be L = \tilde{x}^2. 

Equation 4 is only about the normalization. It has no relationship with loss function. To get the gradient w.r.t. x, we need to get \frac{\partial L}{\partial \tilde{x}} first. Then we use Equation 4 to compute \frac{\partial \tilde{x}}{\partial x}, and then multiply them together (this is the chain-rule, and back-propagation).

It has a same form with Gram-Schmidt orthogonalization when v is \frac{\partial L}{\partial \tilde{x}}, \eta is  \tilde{x} and beta is \frac{\partial L}{\partial x}.

**Comment by kalyo-zjl** [comment]
Using chain rules we can give the gradient to x. Besides, even with normalization, for example that L = \tilde{u}^2 + 2*\tilde{v}^2, then L can be write as L = 1 + v^2/(u^2+v^2), and we also can't get that 
![1](https://user-images.githubusercontent.com/19725489/27720020-581ad7f4-5d89-11e7-9aa4-c7c92554cafe.JPG)
And for Gram-Schmidt orthogonalization, if we use v, \eta and \beta into Equation 4, we will find that it is not Gram-Schmidt orthogonalization actually.

**Comment by happynear** [comment]
u and v are vectors. There is no meaning to normalize a scalar. If u and v are scalars, L=1+2=3 in your example. You can try this kind of loss: L= \sum{\tilde{x}^2}. It would be much easier to infere. However, using chain-rule, we don't need to care about what kind of form L is. We only need to consider the normalization layer's gradient.

It is Gram-Schmidt orthogonalization for the numerator part. Anyway I mention Gram-Schmidt orthogonalization only to let you know the two vectors are orthogonal. If you can infere the equation by yourself, you can just ignore the Gram-Schmidt orthogonalization thing.

**Comment by happynear** [comment]
I don't know if you agree with Equation 4. If you think the formulation of Equation 4 is correct, I can give you a proof that <x, \frac{\partial L}{x}>=0.
![image](https://user-images.githubusercontent.com/3897999/27742831-13cf3a46-5d88-11e7-88a8-c03b972afbb7.png)

The inference of Equation 4 is written in https://github.com/happynear/NormFace/issues/2 .

**Comment by kalyo-zjl** [comment]
Thanks for your kind reply. @happynear 

Maybe I made something wrong, I will look into it deeper.
Thanks.

**Comment by kalyo-zjl** [comment]
Oh, you are right! I think I finally understand it including Figure 4. Since this problem has been solved, I will close it.

Besides, your paper is really helpful for understanding the problem of face verification. I will try your experiment next step.

Thank you again!
