### ISSUE TITLE
Make runtest failed

### ISSUE THREAD

**Issue by nerddd** [happynear/NormFace#12]
The caffe version I use is yours(https://github.com/happynear/caffe-windows/tree/ms).
When I run "make all -j8 &make test -j8",it was alright. But it failed when "make runtest -j8"
The error info lists as follow:
'''
[  FAILED  ] MemoryDataLayerTest/2.TestSetBatchSize, where TypeParam = caffe::GPUDevice<float> (6793 ms)
[ RUN      ] MemoryDataLayerTest/2.AddDatumVectorDefaultTransform
F0711 09:12:00.157285 29234 data_transformer.cpp:189] Check failed: channels == datum_channels (40 vs. 4) 
*** Check failure stack trace: ***
    @     0x2afb9816adaa  (unknown)
    @     0x2afb9816ace4  (unknown)
    @     0x2afb9816a6e6  (unknown)
    @     0x2afb9816d687  (unknown)
    @     0x2afb9ca0eea0  caffe::DataTransformer<>::Transform()
    @     0x2afb9ca0fc7b  caffe::DataTransformer<>::Transform()
    @     0x2afb9caf29bc  caffe::MemoryDataLayer<>::AddDatumVector()
    @           0x621993  caffe::MemoryDataLayerTest_AddDatumVectorDefaultTransform_Test<>::TestBody()
    @           0x8de383  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x8d7387  testing::Test::Run()
    @           0x8d742e  testing::TestInfo::Run()
    @           0x8d7535  testing::TestCase::Run()
    @           0x8d77d8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x8d7a77  testing::UnitTest::Run()
    @           0x46e62f  main
    @     0x2afb9e43bf45  (unknown)
    @           0x476c09  (unknown)
    @              (nil)  (unknown)
'''

**Comment by happynear** [comment]
I don't know how to write test in Linux. Some of my test codes are even written in Matlab. So please ignore the test.
