### ISSUE TITLE
How to compute the distance of two features? 

### ISSUE THREAD

**Issue by scottyyih** [happynear/NormFace#16]

**Comment by happynear** [comment]
Normalize, then compute Euclidean distance.

**Comment by scottyyih** [comment]
Hi Happynear,
Could you please tell me exactly how to do that? Such as show me the formula? I'm new to machine larning. Thanks

**Comment by happynear** [comment]
If you use the provided `face_deploy.prototxt`, the features are already normalized. Then what you should do is only to compute the Euclidean distance `||f1 - f2||` or inner-product `<f1, f2>`.

**Comment by louisWangql** [comment]
Hi Happynear,
Could you please tell me where is the file face_deploy.prototxt?

**Comment by louisWangql** [comment]
Hi Happynear,
Could you please tell me where can download your local files：
net = caffe.Net('E:\Feng\face\l2_distance_contrastive\face_deploy.prototxt','E:\Feng\face\finetune\joint loss\ip+l2\center\weight0.01\face_train_test_iter_10000.caffemodel', 'test');%face_model_my
thanks!

**Comment by happynear** [comment]
They are in the Trained Model section of ReadMe.md.
https://github.com/happynear/NormFace#trained-models

**Comment by senpaipaji** [comment]
There are types of distance which one do you require?
