### ISSUE TITLE
What could i do for python environment?

### ISSUE THREAD

**Issue by charliemorning** [happynear/NormFace#18]
Hello Happnear~

I have deployed the windows version of caffe that come from your repository and I have some reason that i cannot implement a Matlab environment. So i have to use python caffe interface to validate the CenterFace 99.2 Model of Normface. Could I have the correct output as the matlab dose? If not, would u please give me some suggestions?

I saw that the "face_deploy.prototxt" have commented the normalization layer. is that model correct?

Hope for your reply.

Thank u!

Sincerely~~~

**Comment by happynear** [comment]
I am not quite familiar with python. The normalization is added in the Matlab code because I need to apply PCA before normalization. If there is no PCA step(or at least substracting the mean), the accuracy will be a little lower, like 99%.
