### ISSUE TITLE
About the similarity calculation

### ISSUE THREAD

**Issue by waquey** [happynear/NormFace#19]
Hello, I've read your work about norm face. As you've mentioned, when normalization combined with YdWen's center loss work, the accuracy can improve on LFW's 6000 pairs testing.

I'd like to ask:

(1) How can we do the verification on this work?

Extract 'fc5' layer and use this 512 dimension feature vector to calculate cosine similarity directly?

(2) Is there any recommend method to decide the threshold value?

I've found some other works will calculate the similarity and then use the value to judge the accuracy in loop and use the highest score and then decide the threshold value

(3) As Figure 1 shows, does it mean that we don't need to train the mirror image but just use it when in testing scope? And why do the summation of mirror image and the frontal face image can work?

Thanks

**Comment by happynear** [comment]
(1) Yes, cosine similarity.

(2) I use SVM on 9-folds of LFW 6000 pairs to get threshold and test on the other 1-fold. Other methods are also fine. 

(3) The random mirror is added in the training procedure, but the summation is not. The summation is only used during testing. I don't know why it works, its just a trick.
