### ISSUE TITLE
how to infer the formula (4)?

### ISSUE THREAD

**Issue by happynear** [happynear/NormFace#2]
I move the question in https://github.com/happynear/FaceVerification/issues/53 to this repo.

@wuqingshan2010 's question:

> In your paper, i can not infer the formula (4). What does the symbol of “£" represents ? In inferring the formula (4), are there some special skills ? Could you help me ?

**Comment by happynear** [comment]
1. The symbol £ is the final loss. d£/dx means the gradient back-propageted to x. 

2. I write the whole formula inference manually on a paper:

![normalize_gradient](https://cloud.githubusercontent.com/assets/3897999/25400080/7b00ba66-29bf-11e7-9d5d-def3399ea048.jpg)

The key is to treat the norm as an independent variable. This means that we don't need to expand it for the first term of the gradient. The gradient from the norm to x is calculated by the second term. Similar trick is used in Batch Normalization.

**Comment by ZHAIXINGZHAIYUE** [comment]
x_i 与 x_j 分别表示什么呢？

**Comment by happynear** [comment]
@ZHAIXINGZHAIYUE the i-th or j-th number of vector x.

**Comment by lucky-dersan** [comment]
@happynear, thank you, i have understood！
