### ISSUE TITLE
Is there any difference between using a Parameter layer and using normalize: true in InnerDistance layer?

### ISSUE THREAD

**Issue by pipipopo** [happynear/NormFace#23]
Are they equivalent?

**Comment by happynear** [comment]
No. Using Parameter layer means to get a true gradient to the weights. Using normalize: true means to force normalizing the weight during forward.

**Comment by pipipopo** [comment]
@happynear Thanks! Then why the normalized_Euclidean_contrastive.prototxt doesn't use such a Parameter layer?

**Comment by happynear** [comment]
There is not too much difference. Either way is ok.
