### ISSUE TITLE
some question in table2 on your paper

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [happynear/NormFace#3]
what's the means feature only and weight only in table 2?

**Comment by happynear** [comment]
As is their name, normalize the feature only or normalize the weight only.

**Comment by PierreHao** [comment]
I have visualized face normalized features with tsne, it's not 'radial', it's some separated blocks. Your visualization is different from tsne? @happynear

**Comment by happynear** [comment]
t-sne actually changes the distribution.
My visualization is created by modifying the last inner-product layer's output to 2 directly. There is no need to run other dimension reduction algorithms.

BTW...When you are asking a question that has no relationship with the current issue, could you open a new one?

**Comment by PierreHao** [comment]
OK, this question has a relationship with table 2. I will try to do dimension reduction with an added layer on my pretrained face model. Thx.

**Comment by happynear** [comment]
This question is actually related with Figure 2, not table 2.....

**Comment by PierreHao** [comment]
oh my god ...
