### ISSUE TITLE
HI,the test result in LFW only 99.03%.I cann't reach 99.21%

### ISSUE THREAD

**Issue by runauto** [happynear/NormFace#7]
hi, HI,the test result in LFW only reach 99.03%.I cann't reach 99.21%.
the model is( Center Face model(99.21%): Google Drive or Baidu Yun.)
the lfw dataset aligned by your,(http://pan.baidu.com/s/1bp7qzJh)
the extracted feature is "eltmax_fc5"
could you help me ?thanks.

**Comment by happynear** [comment]
I think you have not applied the PCA algorithm on the 9-fold of LFW. The performance before and after PCA is written here https://github.com/happynear/NormFace/blob/master/MirrorFace.md .

**Comment by eglxiang** [comment]
This is good!
